// src/components/EventCard/styles.js
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  
  eventContainer: {
    height: 235,
    width: '100%',
    borderRadius: 10,
    marginBottom: -20,
    position: 'relative',
    overflow: 'hidden',
    marginTop: 60,
    top: -60,
  },
  eventDetails: {
    backgroundColor: '#F26430',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    flex: 1,
    marginTop: 30,
  },
  textContainer: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
  },
  titleContainer: {
    position: 'absolute',
    top: -78,
    left: -2,
    right: 10,
    zIndex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 17,
    padding: 10,
    height: 65,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textBackground: {
    backgroundColor: '#FFFFFF',
    borderRadius: 17,
    width: '100%',
    height: 65,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
  },
  eventImage: {
    width: '40%',
    height: '85%',
    resizeMode: 'stretch',
    borderRadius: 20,
    marginTop: -20,
  },  
  eventTitle: {
    fontSize: 20,
    color: '#000000',
    textAlign: 'center', 
    justifyContent: 'center',
    marginBottom: 5,
  },
  descriptionContainer: {
    position: 'absolute',
    top: -5,
    left: 2,
    right: 12,  
    maxHeight: 100,
    paddingTop: 0,
  },
  eventDescription: {
    fontSize: 14,
    color: '#FFFFFF',
    textAlign: 'justify',
    lineHeight: 20,
    width: '100%',
  },
  
  backgroundEventContainer: {
    position: 'absolute',
    top: 0,
    backgroundColor: '#F8936E',
    height: 100,
    width: '100%',
    borderRadius: 10,
    zIndex: -1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  creatorText: {
    color: '#FFFFFF',
    fontSize: 16,
    position: 'absolute',
    top: 5,
    left: 15,
  },
  cityText: {
    color: '#FFFFFF',
    fontSize: 16,
    position: 'absolute',
    top: 5,
    left: '43%',
    textAlign: 'center',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    top: 7,
    right: 0,
  },
  visibilityIcon: {
    width: 20,
    height: 20,
    position: 'absolute',
    top: 6,
    left: 65,
  },  
  visibilityIconDown: {
    width: 22,
    height: 22,
    position: 'absolute',
    top: 2,
    left: 50,
  },  
  starsText: {
    color: '#FFFFFF',
    fontSize: 16,
    right: 10,
    top: -2,
  },
  starIcon: {
    width: 20,
    height: 20,
    marginRight: 15,
    top: -2,
  },
  dateText: {
    color: '#FFFFFF',
    fontSize: 16,
    right: 3,
    top: 3
  },
  iconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    bottom: 6,
    left: 10,
  },
  iconItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
  },
  icon: {
    width: 25,
    height: 25,
    marginRight: 5,
  },
  iconText: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  dateContainer: {
    position: 'absolute',
    bottom: 10,
    right: 10,
  },
  interBold: {
    fontFamily: 'Inter_700Bold',
  },
  interRegular: {
    fontFamily: 'Inter_400Regular',
  },
});

export default styles;