// src/components/SearchBar/styles.js
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F26430",
    width: "100%",
  },
  header: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
    width: "100%",
    backgroundColor: "#D9D9D9",
    borderRadius: 0,
    height: 45,
  },
  headerText: {
    fontSize: 18,
    justifyContent: "center",
    color: "#000",
    fontWeight: "bold",
    marginTop: -10,
    marginRight: 30,
  },
  dater: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    height: 40,
    marginTop: -25,
    width: "100%",
    backgroundColor: "#F8936E",
    borderRadius: 10,
  },
  dateText: {
    fontSize: 18,
    color: "#000",
    marginTop: 0,
    fontWeight: "bold",
  },
  namer: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    marginLeft: 10,
    height: 50,
    width: "95%",
    backgroundColor: "#FBF6F4",
    borderRadius: 15,
  },
  title: {
    fontSize: 28,
    textAlign: "center",
    fontWeight: "bold",
    paddingTop: 0,
  },
  imagesContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
    width: "100%",
  },
  mapAndImageContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  image: {
    width: "45%",
    height: 190,
    resizeMode: "stretch",
    borderRadius: 14,
    marginRight: 10,
  },
  infoContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    marginHorizontal: 10,
  },
  infoNumAndRating: {
    flexDirection: "row",
    justifyContent: "flex-start",
    width: "47.5%",
  },
  infoTextAprove: {
    fontSize: 22,
    color: "#000",
    borderRadius: 15,
    textAlign: "center",
    fontWeight: "bold",
    marginLeft: 4,
    marginTop: -2,
  },
  mapWrapper: {
    width: "45%",
    height: 190,
    borderRadius: 14,
    overflow: "hidden",
    marginLeft: 10,
    backgroundColor: "#D3D3D3",
  },
  mapContainer: {
    flex: 1,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#D3D3D3",
  },
  map: {
    flex: 1,
    borderRadius: 14,
  },
  infoTextRating: {
    fontSize: 22,
    color: "#000",
    borderRadius: 15,
    textAlign: "center",
    fontWeight: "bold",
    marginLeft: 3,
    marginTop: -2,
  },
  infoTextTitle: {
    fontSize: 22,
    color: "#000",
    borderRadius: 10,
    textAlign: "center",
    fontWeight: "bold",
    marginTop: -4,
    marginRight: 30,
    paddingVertical: 10,
    width: "100%",
    alignSelf: "center",
    textDecorationLine: 'underline',
    flex: 1,
  },  
  infoNum: {
    backgroundColor: "#FBF6F4",
    flex: 2,
    flexDirection: "row",
    borderRadius: 15,
    alignItems: "center", 
    height: 45,
  },
  infoRating: {
    backgroundColor: "#FBF6F4",
    flex: 2,
    flexDirection: "row",
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "flex-start",
    marginLeft: 16,
    height: 45,
  },
  infoTitle: {
    backgroundColor: "#FBF6F4",
    flexDirection: "row",
    borderRadius: 17,
    width: "47.5%",
    height: 45,
    alignItems: "center",
    justifyContent: "center",
  },
  miniiconaprove: {
    marginLeft: 7,
    width: "40%",
    height: "60%",
    resizeMode: "contain",
  },
  miniiconstar: {
    marginLeft: 2,
    width: "40%",
    height: "100%",
    resizeMode: "contain",
  },
  miniicontitle: {
    marginLeft: 10,
    width: 35,
    height: 35,
    borderRadius: 25,
  },
  description: {
    paddingHorizontal: 15,
    paddingVertical: 5,
    fontSize: 22,
    lineHeight: 20,
    color: "#FBF6F4",
    marginBottom: 16,
    flexGrow: 1,
  },
  participationContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
    marginBottom: 20,
  },
  participationText: {
    fontSize: 18,
    marginRight: 8,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: "#FBF6F4",
    borderRadius: 30,
    left: -20,
    height: 50,
    width: 210,
    marginVertical: 0,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 3,
    borderColor: "#000",
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 45,
    borderRadius: 4,
    overflow: "hidden",
  },
  checkboxChecked: {
    backgroundColor: "#FFF",
  },
  checkboxText: {
    fontSize: 14,
    marginLeft: 1,
    color: "black",
    fontWeight: "bold",
    textAlignVertical: "center",
    marginBottom: 1,
  },
  label: {
    fontSize: 22,
    paddingRight: 10,
    color: "#000",
    fontWeight: "bold",
    marginBottom: 3,
  },
  chatContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FBF6F4",
    borderRadius: 30,
    left: 0,
    height: 50,
    width: 100,
    marginLeft: 130,
  },
  chatIcon: {
    left: 20,
  },
  rateButton: {
    backgroundColor: "#F26430",
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 20,
  },
  rateButtonText: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "bold",
  },
  ratingContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: "#FBF6F4",
    borderRadius: 30,
    left: -50,
    height: 80,
    width: 300,
    marginVertical: 50,
  },
  ratingText: {
    fontSize: 22,
    marginBottom: 5,
    marginLeft: 50,
    color: "#000",
  },
  starsContainer: {
    flexDirection: "row",
    marginLeft: 50,
    marginBottom: 10,
  },
  star: {
    width: 30,
    height: 30,
    marginHorizontal: 5,
  },
  starOkContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FBF6F4",
    borderRadius: 30,
    height: 80,
    width: 100,
    right: -40,
    top: 50,
  },
  starOkIcon: {
    left: 20,
  },
  ratingAndOkContainer: {
    flexDirection: "row",
  },
  ratingDisplayContainer: {
    alignItems: "center",
    flexDirection: "row",
    backgroundColor: "#FBF6F4",
    borderRadius: 30,
    height: 50,
    width: 250,
    left: 80,
    marginBottom: 20,
  },
  singleStarContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 5,
  },
  singleStar: {
    width: 30,
    height: 30,
    marginRight: 5,
  },
  ratingNumber: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FBF6F4",
    left: -24,
  },
  nonParticipationContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FBF6F4",
    borderRadius: 30,
    height: 35,
    width: 220,
    alignSelf: "center",
    marginBottom: 20,
  },
  nonParticipationText: {
    fontSize: 20,
    marginBottom: 5,
    color: "#000",
    fontWeight: "600",
  },
  scrollContainer: {
    flex: 1,
  },
  footerContainer: {
    marginTop: 'auto',
    paddingBottom: 20,
  },
  addressContainer: {
    marginVertical: 0,
    paddingHorizontal: 15,
    paddingVertical: 1,
    backgroundColor: "#FBF6F4",
    borderRadius: 15,
    marginHorizontal: 10,
  },
  addressTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 3,
    color: "#F26430",
    textAlign: "center",
  },
  additionalInfoContainer: {
    marginVertical: 15,
    paddingHorizontal: 15,
    paddingVertical: 1,
    backgroundColor: "#FBF6F4",
    borderRadius: 15,
    marginHorizontal: 10,
    flex: 1,
  },
  descriptionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 3,
    color: "#F26430",
    textAlign: "center",
  },
  addressText: {
    fontSize: 16,
    color: "#FFFFFF",
    lineHeight: 15,
    textAlign: "center",
  },
  addressBox: {
    backgroundColor: '#F26430',
    borderColor: '#F26430',
    borderWidth: 2,
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  additionalInfoBox: {
    backgroundColor: '#F26430',
    borderColor: '#F26430',
    borderWidth: 2,
    borderRadius: 10,
    padding: 10,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12
  },
  descriptionText: {
    fontSize: 16,
    color: "#FFFFFF",
    lineHeight: 15,
    textAlign: "center",
  },
  
});

export default styles;
