import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    backgroundColor: "#F26430",
    alignItems: "center",
    justifyContent: "flex-start",
    flex: 1,
    paddingTop: "25%",
    paddingBottom: "20%",
    paddingLeft: "5%",
    paddingRight: "5%",
  },
  modalContainer: {
    flex: 1,
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  mapWrapper: {
    width: 350,
    height: 350,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#D3D3D3",
    borderWidth: 4,
    borderColor: "#000000",
    position: "relative",
  },
  mapContainer: {
    width: "100%",
    height: "100%",
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#D3D3D3",
  },
  map: {
    flex: 1,
    borderRadius: 14,
  },
  mapIconContainer: {
    position: "absolute",
    right: 0,
    top: "55%",
    transform: [{ translateY: -17 }],
  },
  mapIcon: {
    width: 18,
    height: 30,
    tintColor: "black",
    resizeMode: "contain",
  },
  mapErrorText: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    color: "red",
  },
  boxContainer: {
    alignItems: "flex-start",
    justifyContent: "center",
    borderRadius: 30,
    height: "auto",
    width: "100%",
    backgroundColor: "white",
    paddingBottom: 0,
    paddingLeft: "5%",
    paddingRight: "5%",
    marginBottom: 50,
    marginTop: 0,
    flex: 1,
    paddingTop: 20,
  },
  errorContainer: {
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    marginTop: 10,
    marginBottom: -20,
  },
  errorText: {
    color: "red",
    fontSize: 14,
    textAlign: "center",
    alignSelf: "center",
  },
  bottomBoxContainer: {
    marginTop: "auto",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 30,
    height: "auto",
    width: "80%",
    backgroundColor: "white",
    borderWidth: 10,
    borderColor: "#F26430",
    marginLeft: 40,
    marginTop: 30,
    marginBottom: -25,
  },
  bottomBoxText: {
    bottom: 2,
    fontSize: 20,
    fontFamily: "Inter_700Bold",
  },
  iconContainer: {
    paddingLeft: "70%",
    flexDirection: "row",
    marginTop: -55,
  },
  iconeyeandprofile: {
    width: 50,
    height: 50,
  },
  fieldContainer: {
    marginLeft: "20%",
    width: "100%",
    marginVertical: 3,
    top: 35,
  },
  labelContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  labelContainerPhoto: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
    left: 50,
    top: 5,
  },
  fieldContainerDate: {
    marginLeft: "20%",
    width: "100%",
    marginVertical: 3,
    top: 35,
  },
  labelContainerDate: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 0,
  },
  label: {
    fontSize: 18,
    marginBottom: 5,
  },
  input: {
    fontSize: 15,
    placeholderTextColor: "#888",
    borderBottomWidth: 1,
    borderBottomColor: "#000",
    paddingVertical: 1,
    fontFamily: "Inter_700Bold",
  },
  labelPhotoContainer: {
    flexDirection: "row",
    alignItems: "center",
    top: 45,
  },
  labelPhoto: {
    fontSize: 18,
    color: "#F26430",
  },
  fieldContainer: {
    marginLeft: 0,
    width: "100%",
    marginVertical: 5,
    top: 20,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  miniiconphoto: {
    marginRight: 10,
  },
  miniicon: {
    width: 20,
    height: 20,
    marginRight: 10,
  },
  line: {
    height: 1,
    width: "80%",
    backgroundColor: "#000000",
    marginTop: 0,
    bottom: 50,
  },
  loginLinkContainer: {
    marginBottom: 0,
    alignItems: "center",
  },
  loginLinkText: {
    fontSize: 20,
    color: "#F26430",
    textDecorationLine: "underline",
    top: 25,
  },
  modalBackground: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    alignItems: "center",
  },
  closeButton: {
    marginTop: 20,
    padding: 10,
    backgroundColor: "lightblue",
    borderRadius: 5,
  },
  closeButtonText: {
    color: "white",
    fontSize: 16,
  },
  rowContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 15,
    width: "100%",
  },
  halfFieldContainer: {
    flex: 1,
    paddingHorizontal: 0,
    paddingVertical: 0,
    top: 25,
  },
  separator: {
    position: "absolute",
    left: "51%",
    top: 63,
    transform: [{ translateX: -10 }],
  },
  labelPhotoadd: {
    width: 24,
    height: 24,
    marginRight: 4,
  },
  addEventText: {
    fontSize: 26,
    bottom: 13,
    color: "#FFFFFF",
  },
  interBold: {
    fontFamily: "Inter_700Bold",
  },
  interRegular: {
    fontFamily: "Inter_400Regular",
  },
});

export default styles;
